name: 🧩 🐞 Extension Bug Report
description: Report a reproducible bug or regression related to extension(s) published in the Store
title: ""
labels: [extension, bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    attributes:
      label: Extension
      description: |
        Please add a link to the extension concerned by the bug.
        You can search for it in the store: https://raycast.com/store
      placeholder: ex. https://raycast.com/author/extension
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        Please provide a clear and concise description of what the bug is. Include screenshots if needed. Please make sure you are using the latest version of the extension and Raycast.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Your bug will get fixed much faster if the extension author can easily reproduce it. Issues without reproduction steps may be immediately closed as not actionable.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Current Behaviour
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behaviour
    validations:
      required: false
